### ISSUE TITLE
Incorporate a "file-version-info,i" option

### ISSUE THREAD

**Issue by ricardojrdez** [pedrofdez26/windows-memory-extractor#2]
In addition to obtaining the memory content of a module, it is also interesting to obtain the version information of the file to which it corresponds. Once the module is retrieved, ``MODULEENTRY32`` has an attribute (specifically, ``szExePath``) which allows you to get a reference to the corresponding file on disk. With this, you can get the file version information via [GetFileVersionInfo](https://docs.microsoft.com/en-us/windows/win32/api/winver/nf-winver-getfileversioninfoa) and [VerQueryValue](https://docs.microsoft.com/en-us/windows/win32/api/winver/nf-winver-verqueryvaluea) (see some [code examples here](https://cpp.hotexamples.com/examples/-/-/GetFileVersionInfo/cpp-getfileversioninfo-function-examples.html)).

When this option is given, you can generate another file in the output directory (for example, ending with ``.fileinfo`` extension) in which all the possible file version info is saved.

**Comment by pedrofdez26** [comment]
This feature has been added in the commit whose ID is 849190a6e61e229b042c51cd7cc3239508d17fac and is available in the version 1.0.6 of the tool.
